version: '3.8'

services:
  pubsub:
    build: .
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MIX_ENV=prod
      - PHX_HOST=localhost
      - SECRET_KEY_BASE=your-secret-key-base-here-replace-in-production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped